# Generated by Django 3.2.9 on 2022-02-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nomprov', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provincies_4326',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('municipality_id', models.IntegerField(null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=254)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('pertenenci', models.CharField(blank=True, max_length=50, null=True)),
                ('codigoine', models.CharField(blank=True, max_length=20)),
                ('cod_ccaa', models.CharField(blank=True, max_length=2, null=True)),
                ('codprov', models.ForeignKey(db_column='codprov', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.province')),
            ],
            options={
                'db_table': 'municipis_4326',
            },
        ),
        migrations.CreateModel(
            name='MapAuxReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version_uuid', models.CharField(blank=True, max_length=36, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=36)),
                ('observation_date', models.DateTimeField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('ref_system', models.CharField(blank=True, max_length=36)),
                ('type', models.CharField(blank=True, max_length=7)),
                ('expert_validated', models.BooleanField(null=True)),
                ('expert_validation_result', models.CharField(blank=True, max_length=100)),
                ('simplified_expert_validation_result', models.CharField(blank=True, max_length=100)),
                ('site_cat', models.IntegerField(blank=True, null=True)),
                ('storm_drain_status', models.CharField(blank=True, max_length=50)),
                ('edited_user_notes', models.CharField(blank=True, max_length=4000)),
                ('photo_url', models.CharField(blank=True, max_length=255)),
                ('photo_license', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset_license', models.CharField(blank=True, max_length=100, null=True)),
                ('single_report_map_url', models.CharField(blank=True, max_length=255)),
                ('private_webmap_layer', models.CharField(blank=True, max_length=255, null=True)),
                ('final_expert_status', models.IntegerField()),
                ('note', models.TextField()),
                ('tags', models.TextField(null=True)),
                ('breeding_site_answers', models.CharField(blank=True, max_length=100)),
                ('mosquito_answers', models.CharField(blank=True, max_length=100)),
                ('n_photos', models.IntegerField(blank=True, null=True)),
                ('visible', models.BooleanField()),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipality')),
            ],
            options={
                'db_table': 'map_aux_reports',
            },
        ),
    ]
