# Generated by Django 3.2.9 on 2022-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mapauxreport_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfixes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fix_time', models.DateTimeField(blank=True, null=True)),
                ('masked_lon', models.FloatField(blank=True, null=True)),
                ('masked_lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tigaserver_app_fix',
            },
        ),
    ]
