# Generated by Django 3.2.9 on 2022-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userfixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfixes',
            name='mask_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfixes',
            name='phone_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfixes',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfixes',
            name='server_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfixes',
            name='user_coverage_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
