# Generated by Django 3.2.9 on 2022-05-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_anonymoususer_extendeduser_mapview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
