# Generated by Django 3.2.9 on 2022-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_mapview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapview',
            name='code',
            field=models.CharField(default='73cd4b', max_length=6),
        ),
    ]
