# Generated by Django 3.2.9 on 2022-05-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mapview_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='code',
            field=models.CharField(default='967f37', max_length=6, unique=True),
        ),
    ]
