# Generated by Django 4.0.4 on 2022-06-15 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mapauxreport_expert_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.CharField(max_length=5)),
                ('id_2', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('name_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
