# Generated by Django 4.0.4 on 2022-09-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220713_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gadm',
        ),
    ]
