# Generated by Django 4.0.4 on 2022-10-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_gadm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiratingViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days_to_expiration', models.IntegerField(default=365)),
            ],
        ),
    ]
