# Generated by Django 4.0.4 on 2023-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_appsettings_delete_expiratingviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('estimates', 'estimates'), ('wms', 'wms')], default='estimates', max_length=9)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
