# Generated by Django 4.0.4 on 2023-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tabsstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabsstatus',
            name='tab',
            field=models.CharField(choices=[('estimates', 'estimates'), ('wms', 'wms')], default='estimates', max_length=9, unique=True),
        ),
    ]
