# Generated by Django 4.0.4 on 2023-04-21 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_tabsstatus_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('url', models.URLField(max_length=250, verbose_name='URL del servei WMS')),
            ],
        ),
        migrations.CreateModel(
            name='WmsMapLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('wms_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wmsserver')),
            ],
        ),
    ]
