# Generated by Django 4.0.4 on 2023-04-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_wmsmaplayer_name_alter_wmsserver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmsmaplayer',
            name='year',
        ),
    ]
