# Generated by Django 4.0.4 on 2023-04-21 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_wmsmaplayer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsmaplayer',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2020)]),
            preserve_default=False,
        ),
    ]
