# Generated by Django 4.0.4 on 2023-04-22 08:52

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_wmsmaplayer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsmaplayer',
            name='species',
            field=models.CharField(choices=[('tiger', 'Tiger'), ('yellow', 'Yellow'), ('japonicus', 'Japonicus'), ('koreicus', 'Koreicus'), ('culex', 'Culex')], default='tiger', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabsstatus',
            name='tab',
            field=models.CharField(choices=[('estimates', 'Estimates'), ('wms', 'WMS')], default='estimates', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='wmsmaplayer',
            name='year',
            field=models.IntegerField(default=api.models.current_year, validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.AlterUniqueTogether(
            name='wmsmaplayer',
            unique_together={('species', 'year')},
        ),
    ]
