# Generated by Django 4.0.4 on 2023-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_wmsmaplayer_species_alter_tabsstatus_tab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsmaplayer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
