# Generated by Django 4.0.4 on 2023-04-29 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_wmsmaplayer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabsstatus',
            options={'verbose_name': 'Pestanya del frontend', 'verbose_name_plural': 'Pestanyes del frontend'},
        ),
        migrations.AlterModelOptions(
            name='wmsmaplayer',
            options={'verbose_name': 'Capa WMS', 'verbose_name_plural': 'Capes WMS'},
        ),
        migrations.AlterModelOptions(
            name='wmsserver',
            options={'verbose_name': 'Servidor WMS', 'verbose_name_plural': 'Servidorsr WMS'},
        ),
        migrations.AddField(
            model_name='wmsmaplayer',
            name='transparency',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='wmsmaplayer',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
