# Generated by Django 4.0.4 on 2023-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_tabsstatus_options_alter_wmsmaplayer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wmsmaplayer',
            name='transparency',
            field=models.FloatField(default=0),
        ),
    ]
