# Generated by Django 4.0.4 on 2023-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_wmsview_alter_wmsmaplayer_transparency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmsserver',
            options={'verbose_name': 'Servidor WMS', 'verbose_name_plural': 'Servidors WMS'},
        ),
        migrations.AlterField(
            model_name='tabsstatus',
            name='tab',
            field=models.CharField(choices=[('estimates', 'Estimates'), ('distribution', 'Distribution')], default='estimates', max_length=15, unique=True),
        ),
    ]
