# Generated by Django 4.0.4 on 2023-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_wmsview_alter_wmsmaplayer_transparency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmsserver',
            options={'verbose_name': 'Servidor WMS', 'verbose_name_plural': 'Servidors WMS'},
        ),
    ]
