# Generated by Django 4.0.4 on 2023-05-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_wmsserver_options'),
        ('api', '0030_alter_wmsserver_options_alter_tabsstatus_tab'),
    ]

    operations = [
    ]
