# Generated by Django 4.0.4 on 2023-06-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_wmsserver_options_alter_tabsstatus_tab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmsmaplayer',
            options={'verbose_name': 'Capa Distribució', 'verbose_name_plural': 'Capes de la Distribució'},
        ),
    ]
